### ISSUE TITLE
Roadmap #1

### ISSUE THREAD

**Issue by mlbonatelli** [mlbonatelli/SciCommMgz#3]
## Roadmap
_**Empowering our community through interesting and quality science communication**_

This is a _trial version_ of Science Communication Magazine Roadmap. 

### Basics 
- [ ] Name
- [ ] Identity
- [ ] README - **Due to Nov 11**
- [ ] Code of Conduct - **Due to Nov 11**
- [ ] Contributing Guidelines - **Due to Nov 11**

### Website 
This is the place where both readers and authors will meet.
- [ ] How to build a webpage on Github? - **Due to Nov 23**
- [ ] What information does it need?
- [ ] Information to the readers
- [ ] Information to the authors
- [ ] Information to the contributors

Example: https://github.com/Zebetus/studyGroup
https://zebetus.github.io/studyGroup/

### Submission process - **Due to Nov 30**
- [ ] Instructions for authors
- [ ] Google forms
- [ ] Copyright transfer?  
- [ ] User journey (author)

### Process of review - **Due to Dec 6**
The process of review will be open.
- [ ] Deadline?
- [ ] Similar to Mozilla: **creating issue**
- [ ] Other?
- [ ] User journey (reviewer)

### Engaging colaborators 
Where are the collaboratos? How to engaged them into collaborating with the Magazine?
- [ ] HALP :fearful: 

### ASM help
- [ ] Resources from ASM
